version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_beams_otp18
          requires:
            - build
      - build_beams_otp19
          requires:
            - build
      - test_for_otp18
          requires:
            - build_beams_otp18
      - test_for_otp19
          requires:
            - build_beams_otp19

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Setup obeam
          command: opam pin add obeam .
    docker:
      - image: yutopp/obeam-dev-ocaml:latest
  build_beams_otp18: &build_beams_body
    steps:
      - run:
          name: Build beam files for testing
          command: make build-beams
    docker:
      - image: yutopp/obeam-dev-erlang:otp-18
  build_beams_otp19:
    <<: *build_beams_body
    docker:
      - image: erlang:19.3.6.12-slim
  test_for_otp18: &test_body
    steps:
      - run:
          name: Run tests
          command: make test-only
    docker:
      - image: yutopp/obeam-dev-ocaml:latest
  test_for_otp19:
    <<: *test_body
