version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_beams_otp18:
          requires:
            - build
      - build_beams_otp19:
          requires:
            - build
      - test_for_otp18:
          requires:
            - build_beams_otp18
      - test_for_otp19:
          requires:
            - build_beams_otp19

jobs:
  build:
    docker:
      - image: yutopp/obeam-dev-ocaml:latest
    steps:
      - checkout
      - run:
          name: Setup obeam
          command: opam pin add obeam .
      - persist_to_workspace:
          root: /home/opam
          paths:
            - .opam
  build_beams_otp18: &build_beams_body
    working_directory: ~/workspace-otp18
    steps:
      - checkout
      - run:
          name: Build beam files for testing
          command: make build-beams
      - persist_to_workspace:
          root: .
          paths:
            - .
    docker:
      - image: yutopp/obeam-dev-erlang:otp-18
  build_beams_otp19:
    <<: *build_beams_body
    working_directory: ~/workspace-otp19
    docker:
      - image: erlang:19.3.6.12-slim
  test_for_otp18: &test_body
    working_directory: ~/workspace-otp18
    steps:
      - attach_workspace:
          at: .
      - attach_workspace:
          at: /home/opam
      - run:
          name: Run tests
          command: make test-only
    docker:
      - image: yutopp/obeam-dev-ocaml:latest
  test_for_otp19:
    <<: *test_body
    working_directory: ~/workspace-otp19
