version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_beams_otp19:
          requires:
            - build
      - build_beams_otp20:
          requires:
            - build
      - build_beams_otp21:
          requires:
            - build
      - test_for_otp19:
          requires:
            - build_beams_otp19
      - test_for_otp20:
          requires:
            - build_beams_otp20
      - test_for_otp21:
          requires:
            - build_beams_otp21

jobs:
  build:
    docker:
      - image: yutopp/obeam-dev-ocaml:latest
    steps:
      - checkout
      - run:
          name: Setup obeam
          command: opam pin add obeam .
      - save_cache:
          key: opam-{{ arch }}-{{ .Revision }}
          paths:
            - /home/opam/.opam/4.07/bin/dune
            - /home/opam/.opam/4.07/bin/jbuilder
            - /home/opam/.opam/4.07/lib

  build_beams_otp18: &build_beams_body
    working_directory: ~/workspace-otp18
    steps:
      - checkout
      - run:
          name: Build beam files for testing
          command: make build-beams
      - persist_to_workspace:
          root: .
          paths:
            - .
    docker:
      - image: yutopp/obeam-dev-erlang:otp-18

  build_beams_otp19:
    <<: *build_beams_body
    working_directory: ~/workspace-otp19
    docker:
      - image: yutopp/obeam-dev-erlang:otp-19

  build_beams_otp20:
    <<: *build_beams_body
    working_directory: ~/workspace-otp20
    docker:
      - image: yutopp/obeam-dev-erlang:otp-20

  build_beams_otp21:
    <<: *build_beams_body
    working_directory: ~/workspace-otp21
    docker:
      - image: yutopp/obeam-dev-erlang:otp-21

  test_for_otp18: &test_body
    working_directory: ~/workspace-otp18
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: opam-{{ arch }}-{{ .Revision }}
      - run:
          name: Run tests
          command: eval `opam config env` && make test-only
    docker:
      - image: yutopp/obeam-dev-ocaml:latest

  test_for_otp19:
    <<: *test_body
    working_directory: ~/workspace-otp19

  test_for_otp20:
    <<: *test_body
    working_directory: ~/workspace-otp20

  test_for_otp21:
    <<: *test_body
    working_directory: ~/workspace-otp21
